#!/usr/bin/env python3
"""
Generates the sample PDFs the attachment preview loads.

WHY THESE EXIST AT ALL
----------------------
Every PDF fixture used to point at one shared asset,
assets/samples/adverse-media-results.pdf. That was fine while nothing opened
it. It stopped being fine the moment the preview did: our header names the
attachment that was clicked ("call-log-2026-08-11.pdf") while the browser's own
PDF toolbar names the file actually loaded ("adverse-media-results.pdf"), and
the two sat one above the other disagreeing.

Copying the same bytes under each name would have silenced the toolbar and left
the contradiction inside the document, whose footer still says which file it
is. So each named fixture gets its own document instead, with its own title,
its own content and its own footer.

adverse-media-results.pdf is NOT generated here. It shipped first and its four
pages are what verify/preview-pdf.mjs pages through, so it stays exactly as it
is rather than being regenerated by a different writer.

Usage: python3 tools/make-sample-pdfs.py
"""

from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "src" / "assets" / "samples"

# Page furniture, matching the document that shipped first: A4 at 595x842,
# Helvetica, 64pt left margin, title at 742 and body from 712 down.
PAGE_W, PAGE_H = 595, 842
LEFT, TITLE_Y, BODY_Y, FOOTER_Y = 64, 742, 712, 60


def esc(text):
    """PDF strings are parenthesised, so those three characters need escaping."""
    return text.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")


def content_stream(title, lines, footer):
    out = ["BT"]
    if title:
        out += ["/F1 15 Tf", f"1 0 0 1 {LEFT} {TITLE_Y} Tm", "18 TL", f"({esc(title)}) Tj"]
    out += ["/F1 10 Tf", f"1 0 0 1 {LEFT} {BODY_Y} Tm", "15 TL"]
    out += [f"({esc(line)}) Tj T*" for line in lines]
    out += ["/F1 9 Tf", f"1 0 0 1 {LEFT} {FOOTER_Y} Tm", f"({esc(footer)}) Tj", "ET"]
    return "\n".join(out) + "\n"


def build(path, pages):
    """A flat PDF: catalog, page tree, one shared font, then page/content pairs."""
    streams = [content_stream(*p) for p in pages]
    n = len(pages)
    # Objects 4,6,8... are pages; 5,7,9... are their content streams.
    kids = " ".join(f"{4 + i * 2} 0 R" for i in range(n))

    objects = [
        "<< /Type /Catalog /Pages 2 0 R >>",
        f"<< /Type /Pages /Count {n} /Kids [{kids}] >>",
        "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]
    for i, stream in enumerate(streams):
        objects.append(
            f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {PAGE_W} {PAGE_H}] "
            f"/Resources << /Font << /F1 3 0 R >> >> /Contents {5 + i * 2} 0 R >>"
        )
        objects.append(f"<< /Length {len(stream.encode('latin-1'))} >>\nstream\n{stream}endstream")

    body, offsets = "%PDF-1.4\n", []
    for i, obj in enumerate(objects, start=1):
        offsets.append(len(body.encode("latin-1")))
        body += f"{i} 0 obj\n{obj}\nendobj\n"

    # The xref table is byte offsets, so it can only be written once the body
    # above is final - hence building the whole body as a string first.
    start = len(body.encode("latin-1"))
    xref = f"xref\n0 {len(objects) + 1}\n0000000000 65535 f \n"
    xref += "".join(f"{o:010d} 00000 n \n" for o in offsets)
    trailer = f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{start}\n%%EOF\n"

    path.write_bytes((body + xref + trailer).encode("latin-1"))
    print(f"  {path.name}  {len(pages)} pages  {path.stat().st_size} bytes")


SUBJECT = "Subject: Howard Williams  |  Player 88213  |  Case #AML-1042"

CALL_LOG = [
    (
        "Player contact call log",
        [
            SUBJECT,
            "Call placed: 11 Aug 2026, 14:05 UTC    Analyst: A. Kowalski",
            "",
            "CALL DETAILS",
            "Number called: verified mobile on file, ending 4471.",
            "Answered by the account holder. Identity confirmed against three",
            "security questions before any account detail was discussed.",
            "Duration: 11 minutes 20 seconds.",
            "",
            "PURPOSE",
            "Establish source of funds for deposits totalling GBP 42,000 across",
            "the review period, and confirm the player's stated occupation.",
            "",
            "Continued on page 2.",
        ],
        "Page 1 of 2  -  call-log-2026-08-11.pdf",
    ),
    (
        "",
        [
            "SUMMARY OF RESPONSE",
            "Player stated the funds derive from the sale of a residential",
            "property in Bristol, completed 24 Jul 2026. He offered to provide",
            "the completion statement and the solicitor's letter, and agreed a",
            "five working day deadline for doing so.",
            "",
            "Occupation confirmed as self-employed building contractor, which",
            "matches the declaration held on file at registration.",
            "",
            "No reluctance or evasion noted. The player raised no objection to",
            "the review and asked only how long his withdrawals would be held.",
            "",
            "ANALYST ASSESSMENT",
            "Account consistent with the deposit pattern observed. Pending",
            "documentary evidence, no further contact required.",
            "",
            "ATTESTATION",
            "I confirm this log was written from contemporaneous notes taken",
            "during the call, and that no part of it is reconstructed.",
            "",
            "A. Kowalski, Financial Crime Analyst",
            "11 Aug 2026, 14:22 UTC",
            "",
            "SAMPLE DOCUMENT - prototype fixture, not a real call log.",
        ],
        "Page 2 of 2  -  call-log-2026-08-11.pdf",
    ),
]

COMPANIES_HOUSE = [
    (
        "Companies House extract",
        [
            SUBJECT,
            "Retrieved: 11 Aug 2026, 11:05 UTC    Analyst: A. Kowalski",
            "",
            "COMPANY DETAILS",
            "Name: WILLIAMS BUILDING CONTRACTORS LTD",
            "Company number: 09" + "482173",
            "Status: Active",
            "Incorporated: 14 Mar 2015",
            "Registered office: 12 Blackthorn Road, Bristol, BS5 0QD",
            "",
            "NATURE OF BUSINESS (SIC)",
            "41202 - Construction of domestic buildings",
            "",
            "Continued on page 2.",
        ],
        "Page 1 of 3  -  companies-house-extract.pdf",
    ),
    (
        "",
        [
            "OFFICERS",
            "WILLIAMS, Howard James",
            "  Role: Director        Appointed: 14 Mar 2015",
            "  Nationality: British  Occupation: Building contractor",
            "  Date of birth: Feb 1991",
            "",
            "No other appointments, current or resigned.",
            "No disqualifications recorded.",
            "",
            "PERSONS WITH SIGNIFICANT CONTROL",
            "WILLIAMS, Howard James",
            "  Ownership of shares: 75% or more",
            "  Nature of control: right to appoint and remove directors",
            "",
            "One PSC only. No corporate or overseas entity in the structure.",
            "",
            "Continued on page 3.",
        ],
        "Page 2 of 3  -  companies-house-extract.pdf",
    ),
    (
        "",
        [
            "FILING HISTORY (most recent first)",
            "02 Jun 2026   Accounts for period ending 31 Mar 2026",
            "28 Mar 2026   Confirmation statement",
            "05 Jun 2025   Accounts for period ending 31 Mar 2025",
            "29 Mar 2025   Confirmation statement",
            "",
            "All filings made on time. No overdue accounts.",
            "",
            "ANALYST NOTE",
            "The company and the stated occupation agree with the account",
            "declaration. The structure is a single director and single PSC,",
            "with no overseas element requiring further screening.",
            "",
            "ATTESTATION",
            "I confirm this extract was retrieved from the public register on",
            "the date shown and has not been altered.",
            "",
            "A. Kowalski, Financial Crime Analyst",
            "11 Aug 2026, 11:05 UTC",
            "",
            "SAMPLE DOCUMENT - prototype fixture, not a real register extract.",
        ],
        "Page 3 of 3  -  companies-house-extract.pdf",
    ),
]

if __name__ == "__main__":
    print(f"writing to {OUT}")
    build(OUT / "call-log-2026-08-11.pdf", CALL_LOG)
    build(OUT / "companies-house-extract.pdf", COMPANIES_HOUSE)
